### ISSUE TITLE
Liste over deltakere i nettverket.

### ISSUE THREAD

**Issue by knut-erik** [Bouvet-deler/security-champions-rogaland#4]
Flere enhetsledere som etterspør en liste over hvem som er i nettverket, enhet de tilhører og hvor lenge de har vært med.

**Comment by tkalve** [comment]
Her er navn og epost fra Slack-medlemmene pr. i dag. Kanskje Even har en skikkelig liste @knut-erik ?

Navn | E-post
-|-
Adrian Wennberg | adrian.wennberg@bouvet.no
Agnethe Waldejer | agnethe.waldejer@bouvet.no
Aleksander Rekdal Sandbakk | aleksander.sandbakk@bouvet.no
Aleksander Vevle | aleksander.vevle@bouvet.no
Alexandra Aristova | alexandra.aristova@bouvet.no
Anders Lilleheim | anders.lilleheim@bouvet.no
André Kristensen | andre.kristensen@bouvet.no
Anna Reshetnik | anna.reshetnik@bouvet.no
Anne-Marie Fonnes | anne.fonnes@bouvet.no
Annette Fresvik | annette.fresvik@bouvet.no
Arvid Bustad | arvid.bustad@bouvet.no
Atle Fjelde Kristiansen | atle.kristiansen@bouvet.no
Birgit Ramsøy | birgit.ramsoy@bouvet.no
Bjarte Bore | bjarte.bore@olavstoppen.no
Bjarte Botnevik | bjarte.botnevik@bouvet.no
Bjarte Sola | bjarte.sola@bouvet.no
Bjørn Morten B. Brunstøl | bjorn.brunstol@bouvet.no
Camilla Stenersen | camilla.stenersen@bouvet.no
Chris Vikebø | chris.vikebo@bouvet.no
Christoffer Hafsahl | christoffer.hafsahl@bouvet.no
Cveta Krasteva | cveta.krasteva@bouvet.no
Dan André Svendsen | dan.svendsen@bouvet.no
Daniel Bjørke | daniel.bjorke@bouvet.no
Daniel Lundeby | daniel.lundeby@bouvet.no
Daniel N. Hansten | daniel.hansten@bouvet.no
Erik Haugvaldstad | erik.haugvaldstad@bouvet.no
Erik Torkildsen | erik.torkildsen@bouvet.no
Eva Cecilie Peelen | eva.peelen@bouvet.no
Eva Lohndal Midttun | eva.midttun@bouvet.no
Even Tillerli | even.tillerli@bouvet.no
Fateh Alchhabi | fateh.alchhabi@bouvet.no
Geir Ingi Sigurdsson | geir.sigurdsson@bouvet.no
Geir Magne Fossmark | geir.fossmark@bouvet.no
Haakon Hafsahl Svane | haakon.svane@bouvet.no
Hans Kristian Vik Olsen | hans.kristian.olsen@bouvet.no
Hans Røynestad | hans.roynestad@bouvet.no
Helge Nummedal | helge.nummedal@bouvet.no
Henning Negaard Torsteinsen | henning.torsteinsen@bouvet.no
Ina Fløysvik Pedersen | ina.pedersen@bouvet.no
Jacob Vetle Kvinnsland Ihle | jacob.ihle@bouvet.no
Jarl Erik Schmidt | jarl.schmidt@bouvet.no
Joachim Skjæveland | joachim.skjeveland@bouvet.no
John Gustav Kleppa | john.kleppa@bouvet.no
Jon Oftedal Høberg | jon.hoberg@bouvet.no
Jonas Dam | jonas.dam@bouvet.no
Jone Lilleby | jone.lilleby@bouvet.no
Josh Segar | josh.segar@bouvet.no
Karyna Kholodar | karyna.kholodar@bouvet.no
Kenneth Finnesand | kenneth.finnesand@bouvet.no
Kjetil Vinorum | kjetil.vinorum@bouvet.no
Knut Erik Hollund | knut.hollund@bouvet.no
Kristian Nesse | kristian.nesse@bouvet.no
Kristoffer Steen | kristoffer.steen@bouvet.no
Lars Lian | lars.lian@bouvet.no
Leif Bjarte Johansson | leif.johansson@bouvet.no
Marius Mo | marius.mo@bouvet.no
Martin Hauge | martin.hauge@bouvet.no
Merete Løland | merete.loland@bouvet.no
Morten Ladstein | morten.ladstein@bouvet.no
Nadia Bertha Alvarez Reinertsen | nadia.reinertsen@bouvet.no
Nicolas Fløysvik | nicolas.floysvik@bouvet.no
Nicole Silva | nicole.silva@bouvet.no
Nikolai Fosså | nikolai.fossa@bouvet.no
Oda Marie Johannessen | oda.johannessen@bouvet.no
Oddgeir Roalkvam | oddgeir.roalkvam@bouvet.no
Oddvar Nordbø Øksendal | oddvar.oksendal@bouvet.no
Olga Dolgova | olga.dolgova@bouvet.no
René Reinertsen | rene.reinertsen@bouvet.no
Rudi Stene | rudi.stene@bouvet.no
Rupak Katwal | rupak.katwal@bouvet.no
Simon Bay Andersen | simon.andersen@bouvet.no
Sindre Eide Olsen | sindre.olsen@bouvet.no
Sindre Knudsen Smistad | sindre.smistad@bouvet.no
Sindre Reidar Hole Mohr | sindre.mohr@bouvet.no
Ståle Andre Lund | stale.lund@bouvet.no
Sten Otto Johnsen | sten.johnsen@bouvet.no
Sveinung Rørvig | sveinung.rorvig@bouvet.no
Szidonia Antal | szidonia.antal@bouvet.no
Teklemariam Weldehawariat | teklemariam.weldehawariat@bouvet.no
Thomas Kalve | thomas.kalve@bouvet.no
Thomas Kristoffer Olesen Næsje | thomas.naesje@bouvet.no
Thomas Rostrup Andersen | thomas.andersen@bouvet.no
Tommy Kristiansen | tommy.kristiansen@bouvet.no
Tor Kristian Veld | tor.veld@bouvet.no
Tormod Aase | tormod.aase@bouvet.no
Trond Helle Høiland | trond.hoiland@bouvet.no
Vebjørn Espeland | vebjorn.espeland@bouvet.no
Victor Prestholm | victor.prestholm@bouvet.no

**Comment by knut-erik** [comment]
Fant en liste i går som ligger internt, så vi har listen.
Vi bør kanskje ikke ekspenere den her in public @tkalve  :)

**Comment by tkalve** [comment]
> Fant en liste i går som ligger internt, så vi har listen. Vi bør kanskje ikke ekspenere den her in public @tkalve :)

Veldig godt poeng! 🤦

**Comment by knut-erik** [comment]
Closer issue, da vi har funnet oversikten.
